export const deanAnalyticsSampleData = {
  academicYears: ["2026 - 2027"],
  selectedAcademicYear: "2026 - 2027",
  lastUpdated: "Today, 2:30 PM",
  summary: {
    faculties: 128,
    studentResponses: 3842,
    positiveSentimentRate: 84.6,
    courses: 46,
  },
  semesterSentiment: [
    { sentiment: "Positive", firstSemester: 84, secondSemester: 88 },
    { sentiment: "Negative", firstSemester: 9, secondSemester: 6 },
    { sentiment: "Neutral", firstSemester: 7, secondSemester: 6 },
  ],
  overallSentiment: [
    { label: "Positive", value: 172, color: "#5b8cff" },
    { label: "Neutral", value: 13, color: "#d1d5db" },
    { label: "Negative", value: 15, color: "#facc15" },
  ],
  facultyAnalysis: [
    {
      facultyName: "Dr. Amelia Reyes",
      facultyInitials: "AR",
      subjects: [
        "Data Structures",
        "Algorithms",
        "Discrete Mathematics",
        "Automata Theory",
      ],
      overallPositiveRate: "89.4%",
      responses: 412,
    },
    {
      facultyName: "Prof. Marcus Dela Cruz",
      facultyInitials: "MC",
      subjects: [
        "Operating Systems",
        "Computer Networks",
        "Cybersecurity",
      ],
      overallPositiveRate: "85.1%",
      responses: 376,
    },
    {
      facultyName: "Dr. Sofia Mendoza",
      facultyInitials: "SM",
      subjects: [
        "Human Computer Interaction",
        "Software Engineering",
        "Capstone Project",
        "Systems Analysis",
        "Information Management",
      ],
      overallPositiveRate: "91.8%",
      responses: 508,
    },
    {
      facultyName: "Dr. Ethan Navarro",
      facultyInitials: "EN",
      subjects: ["Database Systems", "Data Warehousing", "SQL Programming"],
      overallPositiveRate: "88.2%",
      responses: 441,
    },
    {
      facultyName: "Prof. Liza Fernandez",
      facultyInitials: "LF",
      subjects: ["Web Development", "UI Design", "Frontend Frameworks", "Accessibility"],
      overallPositiveRate: "86.7%",
      responses: 394,
    },
    {
      facultyName: "Dr. Paolo Ramirez",
      facultyInitials: "PR",
      subjects: ["Artificial Intelligence", "Machine Learning", "Deep Learning"],
      overallPositiveRate: "90.5%",
      responses: 467,
    },
    {
      facultyName: "Prof. Nina Torres",
      facultyInitials: "NT",
      subjects: ["Project Management", "IT Governance", "Enterprise Systems"],
      overallPositiveRate: "84.9%",
      responses: 352,
    },
    {
      facultyName: "Dr. Carlo Bautista",
      facultyInitials: "CB",
      subjects: ["Mobile Development", "Android Programming", "iOS Fundamentals"],
      overallPositiveRate: "87.6%",
      responses: 389,
    },
    {
      facultyName: "Prof. Angela Santos",
      facultyInitials: "AS",
      subjects: ["Information Security", "Ethical Hacking", "Digital Forensics"],
      overallPositiveRate: "89.1%",
      responses: 421,
    },
    {
      facultyName: "Dr. Jerome Villanueva",
      facultyInitials: "JV",
      subjects: ["Cloud Computing", "Distributed Systems", "DevOps Practices"],
      overallPositiveRate: "92.3%",
      responses: 476,
    },
    {
      facultyName: "Prof. Hazel Garcia",
      facultyInitials: "HG",
      subjects: ["Business Analytics", "Data Visualization", "Decision Support Systems"],
      overallPositiveRate: "85.8%",
      responses: 365,
    },
    {
      facultyName: "Dr. Miguel Aquino",
      facultyInitials: "MA",
      subjects: ["Research Methods", "Thesis Writing", "Capstone Advising"],
      overallPositiveRate: "88.9%",
      responses: 403,
    },
  ],
} as const;
