/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["HealthController_GetServerHealth_v1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_Login_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AuthController_me_v1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_Refresh_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_Logout_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chatkit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["ChatKitController_Handle_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/enrollments/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user's enrolled courses */
    get: operations["EnrollmentsController_getMyEnrollments_v1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/questionnaires": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new questionnaire */
    post: operations["QuestionnaireController_createQuestionnaire_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/questionnaires/{id}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new version for a questionnaire */
    post: operations["QuestionnaireController_createVersion_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/questionnaires/{id}/latest-active-version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the latest active version for a questionnaire */
    get: operations["QuestionnaireController_getLatestActiveVersion_v1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/questionnaires/versions/{versionId}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Publish a questionnaire version */
    patch: operations["QuestionnaireController_publishVersion_v1"];
    trace?: never;
  };
  "/api/v1/questionnaires/versions/{versionId}/deprecate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Deprecate a questionnaire version */
    patch: operations["QuestionnaireController_deprecateVersion_v1"];
    trace?: never;
  };
  "/api/v1/questionnaires/submissions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit a completed questionnaire */
    post: operations["QuestionnaireController_submitQuestionnaire_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/questionnaires/drafts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a specific draft by query parameters */
    get: operations["QuestionnaireController_getDraft_v1"];
    put?: never;
    /** Save or update a draft questionnaire */
    post: operations["QuestionnaireController_saveDraft_v1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/questionnaires/drafts/list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all drafts for the current user */
    get: operations["QuestionnaireController_listMyDrafts_v1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/questionnaires/drafts/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a draft by ID */
    delete: operations["QuestionnaireController_deleteDraft_v1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LoginRequest: {
      username: string;
      password: string;
    };
    LoginResponse: {
      token: string;
      refreshToken: string;
    };
    MeResponse: {
      id: string;
      userName: string;
      moodleUserId?: number;
      firstName: string;
      lastName: string;
      userProfilePicture: string;
      fullName: string;
      roles: string[];
      campus?: {
        id: string;
        name?: string;
        code: string;
      };
    };
    RefreshTokenRequestBody: {
      refreshToken: string;
    };
    CourseShortResponseDto: {
      id: string;
      moodleCourseId: number;
      shortname: string;
      fullname: string;
    };
    EnrollmentResponseDto: {
      id: string;
      role: string;
      course: components["schemas"]["CourseShortResponseDto"];
    };
    PaginationMeta: {
      totalItems: number;
      itemCount: number;
      itemsPerPage: number;
      totalPages: number;
      currentPage: number;
    };
    MyEnrollmentsResponseDto: {
      data: components["schemas"]["EnrollmentResponseDto"][];
      meta: components["schemas"]["PaginationMeta"];
    };
    CreateQuestionnaireRequest: {
      title: string;
      /** @enum {string} */
      type: "FACULTY_IN_CLASSROOM" | "FACULTY_OUT_OF_CLASSROOM" | "FACULTY_FEEDBACK";
    };
    Questionnaire: {
      title: string;
      /**
       * @default DRAFT
       * @enum {string}
       */
      status: "DRAFT" | "ACTIVE" | "DEPRECATED";
      /** @enum {string} */
      type: "FACULTY_IN_CLASSROOM" | "FACULTY_OUT_OF_CLASSROOM" | "FACULTY_FEEDBACK";
      /** @default [] */
      versions: Record<string, never>;
      /** @default 6977dcd8-a506-4832-ad81-2825839e0c3f */
      id: Record<string, never>;
      /** @default 2026-02-22T09:55:44.955Z */
      createdAt: Record<string, never>;
      /** @default 2026-02-22T09:55:44.955Z */
      updatedAt: Record<string, never>;
      deletedAt?: Record<string, never>;
    };
    CreateVersionRequest: {
      schema: Record<string, never>;
    };
    SubmitQuestionnaireRequest: {
      /** Format: uuid */
      versionId: string;
      /** Format: uuid */
      respondentId: string;
      /** Format: uuid */
      facultyId: string;
      /** Format: uuid */
      semesterId: string;
      /** Format: uuid */
      courseId?: string;
      /**
       * @example {
       *       "q1": 5,
       *       "q2": 4
       *     }
       */
      answers: Record<string, never>;
      qualitativeComment?: string;
    };
    QuestionnaireVersion: {
      questionnaire: components["schemas"]["Questionnaire"];
      versionNumber: number;
      schemaSnapshot: Record<string, never>;
      /** Format: date-time */
      publishedAt?: string;
      /** @default false */
      isActive: boolean;
      /**
       * @default DRAFT
       * @enum {string}
       */
      status: "DRAFT" | "ACTIVE" | "DEPRECATED";
      /** @default 1184eaf1-8c06-4dd1-a4c5-af57e3f3e2a5 */
      id: Record<string, never>;
      /** @default 2026-02-22T09:55:44.959Z */
      createdAt: Record<string, never>;
      /** @default 2026-02-22T09:55:44.959Z */
      updatedAt: Record<string, never>;
      deletedAt?: Record<string, never>;
    };
    Campus: {
      moodleCategoryId: number;
      code: string;
      name?: string;
      /** @default [] */
      semesters: Record<string, never>;
      /** @default 3c94e4b0-8078-4346-bd36-addabdee5edd */
      id: Record<string, never>;
      /** @default 2026-02-22T09:55:44.961Z */
      createdAt: Record<string, never>;
      /** @default 2026-02-22T09:55:44.961Z */
      updatedAt: Record<string, never>;
      deletedAt?: Record<string, never>;
    };
    Semester: {
      moodleCategoryId: number;
      code: string;
      label?: string;
      academicYear?: string;
      campus: components["schemas"]["Campus"];
      /** @default [] */
      departments: Record<string, never>;
      description?: string;
      /** @default 6a0549b8-5cbc-40b7-a90a-941b726c106f */
      id: Record<string, never>;
      /** @default 2026-02-22T09:55:44.962Z */
      createdAt: Record<string, never>;
      /** @default 2026-02-22T09:55:44.962Z */
      updatedAt: Record<string, never>;
      deletedAt?: Record<string, never>;
    };
    Department: {
      moodleCategoryId: number;
      code: string;
      name?: string;
      semester: components["schemas"]["Semester"];
      /** @default [] */
      programs: Record<string, never>;
      /** @default 0f91f3db-6aa1-4419-9699-024a5aeb7bea */
      id: Record<string, never>;
      /** @default 2026-02-22T09:55:44.961Z */
      createdAt: Record<string, never>;
      /** @default 2026-02-22T09:55:44.961Z */
      updatedAt: Record<string, never>;
      deletedAt?: Record<string, never>;
    };
    Program: {
      moodleCategoryId: number;
      code: string;
      name?: string;
      department: components["schemas"]["Department"];
      /** @default [] */
      courses: Record<string, never>;
      /** @default ef93306d-0a68-41fa-8351-e34fa7d1cd0c */
      id: Record<string, never>;
      /** @default 2026-02-22T09:55:44.962Z */
      createdAt: Record<string, never>;
      /** @default 2026-02-22T09:55:44.962Z */
      updatedAt: Record<string, never>;
      deletedAt?: Record<string, never>;
    };
    User: {
      userName: string;
      moodleUserId?: number;
      password?: string;
      firstName: string;
      lastName: string;
      userProfilePicture: string;
      fullName?: string;
      campus?: components["schemas"]["Campus"];
      department?: components["schemas"]["Department"];
      program?: components["schemas"]["Program"];
      /** @default [] */
      moodleTokens: Record<string, never>;
      /** @default [] */
      enrollments: Record<string, never>;
      /** @default [] */
      institutionalRoles: Record<string, never>;
      /** Format: date-time */
      lastLoginAt: string;
      isActive: boolean;
      /** @default [] */
      roles: ("SUPER_ADMIN" | "ADMIN" | "DEAN" | "FACULTY" | "STUDENT")[];
      /** @default fea0d9f1-fc41-4c2b-9fb1-bc94e2e841e0 */
      id: Record<string, never>;
      /** @default 2026-02-22T09:55:44.961Z */
      createdAt: Record<string, never>;
      /** @default 2026-02-22T09:55:44.961Z */
      updatedAt: Record<string, never>;
      deletedAt?: Record<string, never>;
    };
    Course: {
      moodleCourseId: number;
      shortname: string;
      fullname: string;
      program: components["schemas"]["Program"];
      /** Format: date-time */
      startDate: string;
      /** Format: date-time */
      endDate: string;
      isVisible: boolean;
      /** Format: date-time */
      timeModified: string;
      isActive: boolean;
      /** @default 7dbb991b-02fb-4196-b4b7-c13aaba8386c */
      id: Record<string, never>;
      /** @default 2026-02-22T09:55:44.963Z */
      createdAt: Record<string, never>;
      /** @default 2026-02-22T09:55:44.963Z */
      updatedAt: Record<string, never>;
      deletedAt?: Record<string, never>;
    };
    QuestionnaireSubmission: {
      questionnaireVersion: components["schemas"]["QuestionnaireVersion"];
      respondent: components["schemas"]["User"];
      faculty: components["schemas"]["User"];
      /** @enum {string} */
      respondentRole: "STUDENT" | "DEAN";
      semester: components["schemas"]["Semester"];
      course?: components["schemas"]["Course"];
      department: components["schemas"]["Department"];
      program: components["schemas"]["Program"];
      campus: components["schemas"]["Campus"];
      totalScore: number;
      normalizedScore: number;
      qualitativeComment?: string;
      /**
       * Format: date-time
       * @default 2026-02-22T09:55:44.958Z
       */
      submittedAt: string;
      facultyNameSnapshot: string;
      facultyEmployeeNumberSnapshot?: string;
      departmentCodeSnapshot: string;
      departmentNameSnapshot: string;
      programCodeSnapshot: string;
      programNameSnapshot: string;
      campusCodeSnapshot: string;
      campusNameSnapshot: string;
      courseCodeSnapshot?: string;
      courseTitleSnapshot?: string;
      semesterCodeSnapshot: string;
      semesterLabelSnapshot: string;
      academicYearSnapshot: string;
      /** @default [] */
      answers: Record<string, never>;
      /** @default ae1172ac-ab72-4b00-b076-0d6d888770db */
      id: Record<string, never>;
      /** @default 2026-02-22T09:55:44.959Z */
      createdAt: Record<string, never>;
      /** @default 2026-02-22T09:55:44.959Z */
      updatedAt: Record<string, never>;
      deletedAt?: Record<string, never>;
    };
    SaveDraftRequest: {
      /** Format: uuid */
      versionId: string;
      /** Format: uuid */
      facultyId: string;
      /** Format: uuid */
      semesterId: string;
      /** Format: uuid */
      courseId?: string;
      /**
       * @example {
       *       "q1": 5,
       *       "q2": 4
       *     }
       */
      answers: Record<string, never>;
      qualitativeComment?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_GetServerHealth_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  AuthController_Login_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
    };
  };
  AuthController_me_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
    };
  };
  AuthController_Refresh_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshTokenRequestBody"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
    };
  };
  AuthController_Logout_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ChatKitController_Handle_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EnrollmentsController_getMyEnrollments_v1: {
    parameters: {
      query: {
        page: number;
        limit: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MyEnrollmentsResponseDto"];
        };
      };
    };
  };
  QuestionnaireController_createQuestionnaire_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateQuestionnaireRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Questionnaire"];
        };
      };
    };
  };
  QuestionnaireController_createVersion_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateVersionRequest"];
      };
    };
    responses: {
      /** @description Version created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Questionnaire not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Draft version already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuestionnaireController_getLatestActiveVersion_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active version found or null if none exists */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Questionnaire not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuestionnaireController_publishVersion_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        versionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Version published successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Version already published or invalid schema */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Version not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuestionnaireController_deprecateVersion_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        versionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Version deprecated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Version already deprecated */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Version not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuestionnaireController_submitQuestionnaire_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitQuestionnaireRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuestionnaireSubmission"];
        };
      };
    };
  };
  QuestionnaireController_getDraft_v1: {
    parameters: {
      query: {
        versionId: string;
        facultyId: string;
        semesterId: string;
        courseId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Draft found or null if no draft exists for this context */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuestionnaireController_saveDraft_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveDraftRequest"];
      };
    };
    responses: {
      /** @description Draft saved successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid data or inactive version */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuestionnaireController_listMyDrafts_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Drafts retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuestionnaireController_deleteDraft_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Draft deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Draft not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
