export const BUILDER_QUESTION_TYPES = ["LIKERT_1_5", "YES_NO"] as const;

export const DEFAULT_BUILDER_QUESTION_TYPE = "LIKERT_1_5";

export const MAX_SECTION_NESTING_LEVEL = 4;

export const DEFAULT_QUALITATIVE_MAX_LENGTH = 1000;
